name: CheckM2

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      DATADIR: data
    strategy:
        matrix:
            os: ["ubuntu-latest"]
            build_type: [Release]
            compiler: [g++-9]
            include:
              - compiler: g++-9
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge,bioconda
          activate-environment: checkm2
      - name: create initial environment
        run: |
          mamba create -n checkm2 -f checkm2.yml -y
      - name: Activate environment
        run: |
          conda activate checkm2
      - name: package install
        run: python setup.py install
      - name: checkm2 CLI tests
        run: |
            checkm2 -h
            checkm2 predict -h
      - name: checkm2 version
        run: |
            checkm2 --version
#       - name: checkm2 database
#         run: |
#             checkm2 database --download
#       - name: checkm2 testrun
#         run: |
#             checkm2 testrun -t 10
        
